name: Create new issue(创建新 issue)
description: Bug feedback via github templates.(通过 github 模板进行 Bug 反馈。)
title: "Issue title(Issue 标题)"
body:
  - type: markdown
    attributes:
      value: |
        # Welcome to submit issues(欢迎提交issue)

  # - type: input
  #   id: reproduce
  #   attributes:
  #     label: reproduce link(重现链接)
  #     description: Please provide links to CodePen, CodeSandbox or GitHub repositories as minimal as possible. Please do not fill in irrelevant links.(请提供尽可能精简的 CodePen、CodeSandbox 或 GitHub 仓库的链接。)
  #     placeholder: Please fill out(请输入)

  # - type: textarea
  #   id: reproduceSteps
  #   attributes:
  #     label: Steps to reproduce(重现步骤)
  #     description: Please clearly describe the steps to reproduce the issue, which can help us quickly locate the problem.(请清晰的描述重现该 Issue 的步骤，这能帮助我们快速定位问题。)
  #     placeholder: Please fill out(请输入)

  # - type: textarea
  #   id: expect
  #   attributes:
  #     label: Desired result(期望结果)
  #     placeholder: Please fill out(请输入)

  # - type: textarea
  #   id: actual
  #   attributes:
  #     label: Actual results(实际结果)
  #     placeholder: Please fill out(请输入)

  # - type: input
  #   id: frameworkVersion
  #   attributes:
  #     label: Framework version(框架版本)
  #     placeholder: Vue(3.2.0)

  # - type: input
  #   id: nodeVersion
  #   attributes:
  #     label: Node version
  #     placeholder: Please fill out(请输入)

  - type: textarea
    id: remarks
    attributes:
      label: A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository.
        (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)
      placeholder: Please fill out...(请输入...)
